spring.application.name=SpringRestProj04-MiniProject-CRUDOperations

#configure of oracle database
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=lakshman
#spring.datasource.password=865

#embedded server portnumber
server.port=4041
server.servlet.context-path=/RestMiniProject

#jpa cfgs
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sys
spring.datasource.username=springstudent
spring.datasource.password=springstudent
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialet=org.hibernate.dialet.MySQL8Dialet
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update