spring.application.name=BootJPAProj01-CrudRepository

# data source configuration
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=lakshman
#spring.datasource.password=865
#spring.datasource.hikari.minimum-idle=10
#spring.datasource.hikari.maximum-pool-size=100

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///sys
spring.datasource.username=root
spring.datasource.password=Lakshman$#865
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=100

#JPA-hibernate properties
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update