spring.application.name=BulkInjection-DBs

schema1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
schema1.datasource.jdbc-url=jdbc:mysql://localhost:3306/schema_01
schema1.datasource.username=springstudent
schema1.datasource.password=springstudent


schema2.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
schema2.datasource.jdbc-url=jdbc:mysql://localhost:3306/schema_02
schema2.datasource.username=springstudent
schema2.datasource.password=springstudent