spring.application.name=Bootproj04-RealTimeproject-LayeredAppHotel

#oracle jdbc properties to make DataSource(AutoConfiguration)object pointing to jdbc con pool for oracle
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=lakshman
#spring.datasource.password=865

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sys
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialet=org.hibernate.dialet.MySQL8Dialet
